apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  labels:
    app: nginx-pod
    type: frontend
spec:
  containers:
  - name: nginx-con
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  resources:
    requests: # Only limits are specfied requests == limits
      memory: "1Gi" # "256Mi"
      cpu: "200m"
    limits:
      memory: "2Gi" # Can use more than what is allocated, but application will terminated saying OOM(Out of Memory)
      cpu: 1 # Can't use more CPU, application throttle
...
apiVersion: v1
kind: pod
metadata:
  name: ubuntu-sleeper
  labels:
    os: ubuntu
spec:
  containers:
    - name: ubuntu-sleeper
      image: ubuntu-sleeper
      command: ["sleep2.0"] # Related to ENTRYPOINT in Dockerfile
      args: ["3"] # Related to CMD in Dockerfile
      # command: # This is also valid
      # - "sleep2.0"
      # - "3"
      env: # Environemnt variable
      - name: color
        value: pink
