apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-app
  labels:
    app: my-app
    type: frontend
spec:
  template:
    metadata:
      name: my-app
      labels:
        app: my-app
        type: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
  replicas: 2
  selector:
    matchLabel:
      type: frontend
