apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-volume
spec:
  capacity:
    storage: 1Gi
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/volume/nginx
  claimRef:
    name: foo-pvc
    namespace: foo
...
